export const ResourcesData = [
    { id: 1, title: 'To Kill a Mockingbird', author: 'Harper Lee', image: 'https://th.bing.com/th/id/OIP.6eMcUSp7g-eVTJ9eR0sYegHaKj?w=182&h=260&c=7&r=0&o=5&dpr=1.3&pid=1.7', description: 'A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in a South poisoned by virulent prejudice.' },
    { id: 2, title: '1984', author: 'George Orwell', image: 'https://images.unsplash.com/photo-1579546927553-5b5cf36ec80b', description: 'The story of Winston Smith, an outwardly obedient citizen of Airstrip One, whose actions reveal his opposition to the totalitarian control of Big Brother and The Party.' },
    { id: 3, title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', image: 'https://images.unsplash.com/photo-1591697759618-df99ca9a4f1e', description: 'The Great Gatsby, F. Scott Fitzgerald’s third book, stands as the supreme achievement of his career.' },
    { id: 4, title: 'Pride and Prejudice', author: 'Jane Austen', image: 'https://images.unsplash.com/photo-1518644735594-14b921c4db35', description: 'Pride and Prejudice is a romantic novel of manners written by Jane Austen in 1813.' },
    { id: 5, title: 'The Catcher in the Rye', author: 'J.D. Salinger', image: 'https://images.unsplash.com/photo-1590134780543-04b31a3af2ba', description: 'Holden Caulfield, a sixteen-year-old boy from New York City, tells the story of three days in his life when he was sixteen.' },
    { id: 6, title: 'Brave New World', author: 'Aldous Huxley', image: 'https://images.unsplash.com/photo-1608230488781-6a5a2811e66b', description: 'Aldous Huxley is rightly considered a prophetic genius and one of the most important literary and philosophical voices of the 20th Century.' },
    { id: 7, title: 'The Hobbit', author: 'J.R.R. Tolkien', image: 'https://images.unsplash.com/photo-1543363136-45258d308de9', description: 'The Hobbit is set within Tolkien\'s fictional universe and follows the quest of home-loving Bilbo Baggins.' },
    { id: 8, title: 'The Lord of the Rings', author: 'J.R.R. Tolkien', image: 'https://images.unsplash.com/photo-1589998871457-3a3370a6c887', description: 'The Lord of the Rings is an epic high-fantasy novel by English author and scholar J. R. R. Tolkien.' },
    { id: 9, title: 'Moby-Dick', author: 'Herman Melville', image: 'https://images.unsplash.com/photo-1605790053171-288b5b9dd3e3', description: 'Moby-Dick is an 1851 novel by American writer Herman Melville. The book is the sailor Ishmael\'s narrative of the obsessive quest of Ahab, captain of the whaling ship Pequod, for revenge on Moby Dick, the giant white sperm whale that on the ship\'s previous voyage bit off Ahab\'s leg at the knee.' },
    { id: 10, title: 'The Odyssey', author: 'Homer', image: 'https://images.unsplash.com/photo-1553009977-84c1f8d0223b', description: 'The Odyssey is one of two major ancient Greek epic poems attributed to Homer. It is, in part, a sequel to the Iliad, the other Homeric epic.' },
    { id: 11, title: 'Frankenstein', author: 'Mary Shelley', image: 'https://images.unsplash.com/photo-1601000650389-d1266d1177ff', description: 'Frankenstein; or, The Modern Prometheus is a novel written by English author Mary Shelley. It tells the story of Victor Frankenstein, a young scientist who creates a sapient creature in an unorthodox scientific experiment.' },
    { id: 12, title: 'Alice\'s Adventures in Wonderland', author: 'Lewis Carroll', image: 'https://images.unsplash.com/photo-1597155336868-6a6b722ad4e0', description: 'Alice\'s Adventures in Wonderland is an 1865 novel by English author Lewis Carroll. It tells of a young girl named Alice falling through a rabbit hole into a fantasy world populated by peculiar, anthropomorphic creatures.' }
]